### ISSUE TITLE
Nit: don't use snake case for package names

### ISSUE THREAD

**Issue by leodamskii** [KickScooterTeam/kick-scooter-messaging#12]
https://github.com/KickScooterTeam/kick-scooter-messaging/blob/a7812a54e44eeb13f167a836416ca4143e1b21cb/src/main/java/com/softserve/message_sender/MessageSenderApplication.java#L1

Package names of multiple words aren't usually separated e.g. `org.springframework.mail.javamail.JavaMailSender`

**Comment by edgar-kr** [comment]
noted
