### ISSUE TITLE
Nit: Use SLF4J unless you need logger implementation specific features

### ISSUE THREAD

**Issue by leodamskii** [KickScooterTeam/kick-scooter-messaging#3]
https://github.com/KickScooterTeam/kick-scooter-messaging/blob/a7812a54e44eeb13f167a836416ca4143e1b21cb/src/main/java/com/softserve/message_sender/service/KafkaConsumer.java#L13
https://github.com/KickScooterTeam/kick-scooter-messaging/blob/a7812a54e44eeb13f167a836416ca4143e1b21cb/src/main/java/com/softserve/message_sender/service/MailServiceImpl.java#L15

**Comment by edgar-kr** [comment]
done
