### ISSUE TITLE
Nit: star imports are not recommended

### ISSUE THREAD

**Issue by leodamskii** [KickScooterTeam/kick-scooter-messaging#4]
https://github.com/KickScooterTeam/kick-scooter-messaging/blob/a7812a54e44eeb13f167a836416ca4143e1b21cb/src/main/java/com/softserve/message_sender/controller/MessageController.java#L9

Star imports make harder to overview used classes. Usually, they are prohibited.

**Comment by edgar-kr** [comment]
done
